# Generated by Django 4.0.5 on 2022-07-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ParseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('start_parse', models.DateTimeField(blank=True, null=True)),
                ('end_parse', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_page', models.FileField(blank=True, null=True, upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.parsejob')),
            ],
        ),
        migrations.CreateModel(
            name='BannerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_url', models.CharField(max_length=1000, null=True)),
                ('image_url', models.CharField(max_length=1000, null=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.banner')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.page'),
        ),
    ]
