# Generated by Django 4.0.5 on 2022-07-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_page_pageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='page',
            new_name='pageurl',
        ),
    ]
