# Generated by Django 4.0.5 on 2022-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_page_banner_pageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdata',
            name='click_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerdata',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
