# Generated by Django 4.0.5 on 2022-07-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_bannerdata_click_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='click_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='BannerData',
        ),
    ]
